Attempt to download pre-built binaries (#16)
When `binary-url-template` is specified the expanded template is checked
for an existing binary. When found, that binary is installed and no
build or cache is performed.

```yaml
steps:
- uses: reconcilerio/go-install-action@v1
  with:
  package: sigs.k8s.io/kustomize/kustomize/v5
  binary-url-template: https://github.com/kubernetes-sigs/kustomize/releases/download/kustomize%2F${version}/kustomize_${version}_${os}_${arch}.tar.gz
  binary-path-within-archive: kustomize
- run: kustomize --help
```

Signed-off-by: Scott Andrews <scott@andrews.me>

diff --git a/action.yml b/action.yml
--- a/action.yml
+++ b/action.yml
@@ -15,6 +15,10 @@ inputs:
     default: '.'
   toolchain:
     description: override GOTOOLCHAIN for this build
+  binary-url-template:
+    description: URL template to resolve a pre-built binary. If the expanded URL resolves to an artifact, no artifact will be built or cached.
+  binary-path-within-archive:
+    description: Path within an archive resolved by binary-url-template.
   output:
     description: name of the built binary
   output-dir:
@@ -136,9 +140,39 @@ runs:
       echo "toolchain=${toolchain}" >> "${GITHUB_OUTPUT}"
     shell: bash
     working-directory: ${{ inputs.working-directory }}
+  - name: Attempt download
+    id: download
+    if: inputs.binary-url-template != ''
+    run: |
+      set -euo pipefail
+
+      os="$(go env GOOS)"
+      arch="$(go env GOARCH)"
+      version="${{ steps.prep.outputs.normalized-version }}"
+
+      url=$(eval echo "${{ inputs.binary-url-template }}")
+
+      cache_dir="${{ steps.prep.outputs.cache-dir }}"
+      name="$(basename "${{ inputs.package }}")"
+      path_within="${{ inputs.binary-path-within-archive }}"
+
+      echo "Checking URL ${url}"
+      if curl -sSL --fail "${url}" -o "${cache_dir}/.download" ; then
+        if [[ -n "${path_within}" ]] ; then
+          trap 'rm "${cache_dir}/.download"' EXIT
+          tar -xf "${cache_dir}/.download" -C "${cache_dir}" "${path_within}" || exit 0
+        else
+          mv "${cache_dir}/.download" "${cache_dir}/${name}"
+        fi
+        echo "provenance=download" >> "${GITHUB_OUTPUT}"
+      else
+        echo "Download failed with exit code $?"
+      fi
+
+    shell: bash
   - name: Check workflow cache
     id: workflow-cache
-    if: inputs.cache-enabled != 'false'
+    if: inputs.cache-enabled != 'false' && steps.download.outputs.provenance != 'download'
     uses: actions/download-artifact@v8
     with:
       name: "${{ steps.prep.outputs.artifact-key }}"
@@ -146,14 +180,14 @@ runs:
     continue-on-error: true
   - name: Cache
     id: cache
-    if: inputs.cache-enabled != 'false' && steps.workflow-cache.outcome != 'success'
+    if: inputs.cache-enabled != 'false' && steps.workflow-cache.outcome != 'success' && steps.download.outputs.provenance != 'download'
     uses: actions/cache@v5
     with:
       key: "${{ steps.prep.outputs.cache-key }}"
       path: "${{ steps.prep.outputs.cache-dir }}"
   - name: Build
     id: build
-    if: steps.cache.outputs.cache-hit == '' && steps.workflow-cache.outcome != 'success'
+    if: steps.cache.outputs.cache-hit == '' && steps.workflow-cache.outcome != 'success' && steps.download.outputs.provenance != 'download'
     run: |
       set -euo pipefail
 
@@ -183,7 +217,7 @@ runs:
     shell: bash
     working-directory: ${{ inputs.working-directory }}
   - name: Seed workflow cache
-    if: success() && steps.workflow-cache.outcome != 'success' && inputs.cache-enabled != 'false'
+    if: success() && steps.workflow-cache.outcome != 'success' && inputs.cache-enabled != 'false' && steps.download.outputs.provenance != 'download'
     uses: actions/upload-artifact@v7
     with:
       name: "${{ steps.prep.outputs.artifact-key }}"
@@ -215,6 +249,6 @@ runs:
       if [[ "${output_path_env}" != "" ]] ; then
         echo "${output_path_env}=${path}" >> "${GITHUB_ENV}"
       fi
-      echo "provenance=${{ steps.build.outputs.provenance || 'cache' }}" >> "${GITHUB_OUTPUT}"
+      echo "provenance=${{ steps.download.outputs.provenance || steps.build.outputs.provenance || 'cache' }}" >> "${GITHUB_OUTPUT}"
     shell: bash
     working-directory: ${{ inputs.working-directory }}
